In [ ]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
df_post = pd.read_csv("../data/processed/cleaned_eth_post.csv")
df_post.head()

,Unnamed: 0,created_utc,subreddit,body,score,Date
0,0,1579408968,ethereum,Yeah that s infallible Logic you re using there,6,2020-01-19
1,1,1579408860,ethereum,RemindMe 6 Months,3,2020-01-19
2,2,1579408651,ethereum,Thats what people said here about 2018 and 2019,-5,2020-01-19
3,3,1579408630,ethereum,My comment is 100 accurate According to th...,-13,2020-01-19
4,4,1579407990,ethereum,Risk of a smart contract being hacked If ther...,2,2020-01-19

In [3]:
# Standardize the body
df_post["body"] = df_post["body"].str.lower()
df_post.head()

,Unnamed: 0,created_utc,subreddit,body,score,Date
0,0,1579408968,ethereum,yeah that s infallible logic you re using there,6,2020-01-19
1,1,1579408860,ethereum,remindme 6 months,3,2020-01-19
2,2,1579408651,ethereum,thats what people said here about 2018 and 2019,-5,2020-01-19
3,3,1579408630,ethereum,my comment is 100 accurate according to th...,-13,2020-01-19
4,4,1579407990,ethereum,risk of a smart contract being hacked if ther...,2,2020-01-19

In [11]:
# Get Sentiment Score

sentiment_model = SentimentIntensityAnalyzer()

df_post["vader_scores"] = df_post['body'].apply(lambda x: sentiment_model.polarity_scores(x)["compound"]) 

df_post.head()

,Unnamed: 0,created_utc,subreddit,body,score,Date,vader_scores
0,0,1579408968,ethereum,yeah that s infallible logic you re using there,6,2020-01-19,0.2960
1,1,1579408860,ethereum,remindme 6 months,3,2020-01-19,0.0000
2,2,1579408651,ethereum,thats what people said here about 2018 and 2019,-5,2020-01-19,0.0000
3,3,1579408630,ethereum,my comment is 100 accurate according to th...,-13,2020-01-19,-0.2023
4,4,1579407990,ethereum,risk of a smart contract being hacked if ther...,2,2020-01-19,0.2732

In [12]:
# Save to csv

df_post.to_csv("../data/processed/cleaned_eth_post.csv")